apiVersion: v2
name: contextforge
description: A Kubernetes operator for automatic HTTP header propagation via sidecar injection
type: application
version: 0.1.1
appVersion: "0.1.1"
keywords:
  - kubernetes
  - operator
  - sidecar
  - header-propagation
  - tracing
home: https://github.com/bgruszka/contextforge
sources:
  - https://github.com/bgruszka/contextforge
maintainers:
  - name: Blazej Gruszka
    email: blazej@gruszka.info
