# This rule is not used by the project contextforge itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over ctxforge.ctxforge.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: contextforge
    app.kubernetes.io/managed-by: kustomize
  name: headerpropagationpolicy-admin-role
rules:
- apiGroups:
  - ctxforge.ctxforge.io
  resources:
  - headerpropagationpolicies
  verbs:
  - '*'
- apiGroups:
  - ctxforge.ctxforge.io
  resources:
  - headerpropagationpolicies/status
  verbs:
  - get
