# This rule is not used by the project contextforge itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to ctxforge.ctxforge.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: contextforge
    app.kubernetes.io/managed-by: kustomize
  name: headerpropagationpolicy-viewer-role
rules:
- apiGroups:
  - ctxforge.ctxforge.io
  resources:
  - headerpropagationpolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ctxforge.ctxforge.io
  resources:
  - headerpropagationpolicies/status
  verbs:
  - get
